/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LoginData } from "./components/login-form/login-form-data";
import { User } from "./components/user-list/user-list";
export namespace Components {
    interface LoginForm {
    }
    interface NxextLogo {
    }
    interface SiteNavigation {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface UserHome {
    }
    interface UserList {
        "users": User[];
    }
}
declare global {
    interface HTMLLoginFormElement extends Components.LoginForm, HTMLStencilElement {
    }
    var HTMLLoginFormElement: {
        prototype: HTMLLoginFormElement;
        new (): HTMLLoginFormElement;
    };
    interface HTMLNxextLogoElement extends Components.NxextLogo, HTMLStencilElement {
    }
    var HTMLNxextLogoElement: {
        prototype: HTMLNxextLogoElement;
        new (): HTMLNxextLogoElement;
    };
    interface HTMLSiteNavigationElement extends Components.SiteNavigation, HTMLStencilElement {
    }
    var HTMLSiteNavigationElement: {
        prototype: HTMLSiteNavigationElement;
        new (): HTMLSiteNavigationElement;
    };
    interface HTMLUserHomeElement extends Components.UserHome, HTMLStencilElement {
    }
    var HTMLUserHomeElement: {
        prototype: HTMLUserHomeElement;
        new (): HTMLUserHomeElement;
    };
    interface HTMLUserListElement extends Components.UserList, HTMLStencilElement {
    }
    var HTMLUserListElement: {
        prototype: HTMLUserListElement;
        new (): HTMLUserListElement;
    };
    interface HTMLElementTagNameMap {
        "login-form": HTMLLoginFormElement;
        "nxext-logo": HTMLNxextLogoElement;
        "site-navigation": HTMLSiteNavigationElement;
        "user-home": HTMLUserHomeElement;
        "user-list": HTMLUserListElement;
    }
}
declare namespace LocalJSX {
    interface LoginForm {
        "onLoginDataEvent"?: (event: CustomEvent<LoginData>) => void;
    }
    interface NxextLogo {
    }
    interface SiteNavigation {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface UserHome {
    }
    interface UserList {
        "users"?: User[];
    }
    interface IntrinsicElements {
        "login-form": LoginForm;
        "nxext-logo": NxextLogo;
        "site-navigation": SiteNavigation;
        "user-home": UserHome;
        "user-list": UserList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "login-form": LocalJSX.LoginForm & JSXBase.HTMLAttributes<HTMLLoginFormElement>;
            "nxext-logo": LocalJSX.NxextLogo & JSXBase.HTMLAttributes<HTMLNxextLogoElement>;
            "site-navigation": LocalJSX.SiteNavigation & JSXBase.HTMLAttributes<HTMLSiteNavigationElement>;
            "user-home": LocalJSX.UserHome & JSXBase.HTMLAttributes<HTMLUserHomeElement>;
            "user-list": LocalJSX.UserList & JSXBase.HTMLAttributes<HTMLUserListElement>;
        }
    }
}
